apiVersion: v1
kind: Service
metadata:
  name: max-image-segmenter
spec:
  selector:
    app: max-image-segmenter
  ports:
  - name: api
    port: 5000
    nodePort: 30050
  - name: web
    port: 3000
    nodePort: 30030
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: max-image-segmenter
  labels:
    app: max-image-segmenter
spec:
  selector:
    matchLabels:
      app: max-image-segmenter
  replicas: 1
  template:
    metadata:
      labels:
        app: max-image-segmenter
    spec:
      containers:
      - name: max-image-segmenter
        image: codait/max-image-segmenter:latest
        ports:
        - containerPort: 5000
        env:
        - name: CORS_ENABLE
          value: "true"
      - name: max-image-segmenter-web
        image: kastentx/kube-imgseg-app
        ports:
        - containerPort: 3000
        env:
        - name: CORS_ENABLE
          value: "true"
        - name: REACT_APP_KUBE_MODEL_PORT
          value: "30050"
        - name: REACT_APP_KUBE_IP
          value: "184.172.250.9"
        - name: REACT_APP_DEPLOY_TYPE
          value: "KUBE"
